name: Build project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Setup cache
        uses: bahmutov/npm-install@HEAD
      - name: Install dependencies
        run: npm t
      - name: Test and build code
        run: npm run validate
      - name: Upload test reports
        uses: codecov/codecov-action@v1
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          branches: |
            [
              'master',
              {
                name: 'beta',
                prerelease: true
              }
            ]
